name: continuous integration
run-name: Testing continuous integrtion

on: [push]

env:
  owner_name: Vini 
  host : ${{ secrets.HOST }}
  port : ${{ secrets.PORT }}
  username : ${{ secrets.USERNAME }}
  token : ${{ secrets.TOKEN }}

jobs:
  use_env_var:
    runs-on: ubuntu-latest
     steps:
       - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://$host:$port"
        user: "$username"
        token: $token
        job: "devop_assignment"

