name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://15.207.72.90:8080"
        user: "admin"
        token: "11b3fa6d90534b7928d80e90f8550b8d77"
        job: "devop_assignment"

